/**
 * Straightforward attempt to dynamically load a kernel module attached to the initial binary image
 */
#include "IDynamicLoadingImpl.h"
#include "LDComponent.h"
#include "elf.h"
#include "Boot/memlayout.h"
#include "IContext.h"

#include "debug.h"
#include "MT/Thread.h"// debug only

/**
 * The structure generated by dlltool, reverse engineered (use '-n' option to see generated asm)
 *
 * .long    0   # Allways 0
    .long   0x48abdc91  # Time and date
    .long   0   # Major and Minor version
    .rva    name    # Ptr to name of dll
    .long   1   # Starting ordinal of exports
    .long   4   # Number of functions
    # named funcs 4, low ord 1, high ord 4
    .long   4   # Number of names
    .rva    afuncs  # Address of functions
    .rva    anames  # Address of Name Pointer Table
    .rva    anords  # Address of ordinals

    "RVA" means "relative virtual address", it is the virtual address minus the base.
    Need to set "--image-base 0" in ld to make this work!
 */
extern "C" struct ExportTable {
    u32 _zero;
    u32 timedate;
    u32 version;
    const char* const dllName;
    u32 firstOrdinal;   // for windows: ordinal-based exporting. Yuck!
    u32 numberOfExports;
    u32 numberOfNames;
    u32* functionAddressTable;
    const char* const * const *functionNameTable;
    u16* ordinalTable;  // Abuse this as counters on how often they are exported
} _EXPORT_TABLE_;  // linker constant

// extern "C" void* _EXPORT_TABLE_;

namespace MyOS {
namespace DynamicLoading {

/**
 * Calculates the order of pages (2^o) required for the given number of bytes
 */
inline static unsigned bytes2order( unsigned bytes )
{
    // Determine highest set bit
    unsigned highest = 31;
    for (unsigned mask = (1<<31); mask; mask >>= 1, --highest) {
        if ( bytes & mask ) {
            if ( bytes & ~mask ) {
                ++highest;
            }
            return (highest>12) ? highest - 12 : 0;   // 1 page = 1^12 bits
        }
    }
}

IDynamicLoadingImpl::IDynamicLoadingImpl( MyOS::Core::IComponent& c )
: IDynamicLoading( c, VERSION(1,0) )
{

}


/**
 * MyOS (needs to) take a different approach than Linux
 *
 * 1) use 'declspec( dllexport )' on exported symbols (both classes and functions);
 *    this causes gcc to generate a ".drectve" with ASCII-based linker commands
 * 2) use 'dlltool -e exports.elf build/debug/Core/libAllObjs.a' to generate an ELF export table
 * 3) Link exports.elf into the kernel to resolve the exported addresses
 * 4) Read those tables here
 *
 * Linux does not to deal with C++ mangled names, and exported classes
 *
 */

static u32 resolveKernelSymbol( const char* const name ) {

    ExportTable &et = _EXPORT_TABLE_;

    // Simplest: linear search. Can do binary/hash search later
    for ( int i = 0; i<et.numberOfExports; ++i ) {
        // DPRINTK( "\nFunction %s @ %x", et.functionNameTable[p], et.functionAddressTable[p] );
        if ( strcmp( (const char*) et.functionNameTable[i], name ) == 0 ) {
            // ++et.ordinalTable[i];   // keep count of how often exported

            // This is wrong! Ordinal order may differ from export indices!!
            // return et.functionAddressTable[i];
            return et.functionAddressTable[ et.ordinalTable[i] ];
        }
    }

    DPRINTK( "\n#4e#Unable to resolve kernel symbol: %s", name );
    return 0;
}

/**
 * Determines the accumulated size of all code sections (.text*), and relocates
 * the memory to an executable area of linear memory
 *
 * @return delta offset in virtual memory
 */
static Elf32_Off relocateCode( const Elf32_Ehdr &elfHdr )
{
    int i=0;
    Elf32_Off minOffset = 0xffffffff, maxOffset = 0;
    for ( u8* ph = ((u8*)&elfHdr) + elfHdr.e_shoff; i < elfHdr.e_shnum; ph += elfHdr.e_shentsize, ++i) {
        Elf32_Shdr *sh = (Elf32_Shdr*) ph;
        if (( sh->sh_type == SHT_PROGBITS ) && (sh->sh_flags & SHF_EXECINSTR) ) {
            if ( sh->sh_offset < minOffset ) minOffset = sh->sh_offset;
            if ( (sh->sh_offset + sh->sh_size) > maxOffset ) maxOffset = sh->sh_offset + sh->sh_size;
        }
    }
    // DPRINTK( "\nMinOffset:%u maxOffset: %u", minOffset, maxOffset );
    unsigned order = bytes2order( maxOffset-minOffset );
    IVirtualMemory *vm = LDComponent::getInstance().iVirtualMemory;
    u32 *code = (u32*) vm->mmap(order, true);
    vm->copyMapping(code, ((u8*) &elfHdr) + minOffset, 1UL << order,
            MM::E_PAGE_SHAREABLE | MM::E_PAGE_READONLY);
    // DPRINTK("\nAllocated .code@%x (2^%u pages)", code, order);
    return ((Elf32_Off) code) - (Elf32_Off) &elfHdr;
}

bool
IDynamicLoadingImpl::loadModule( /* Elf32_Ehdr &*/ const u8* const elf, Context::IContext &context )
{
    /* Test: dump exported names
    ExportTable &et = _EXPORT_TABLE_;
    DPRINTK( "\n#exports: %u names@%x", et.numberOfExports, et.functionNameTable );
    for ( int p = 0; p<et.numberOfExports; ++p ) {
        DPRINTK( "\nFunction %s @ %x", et.functionNameTable[p], et.functionAddressTable[p] );
    }*/

    // Clear counters
    // memset_aligned( _EXPORT_TABLE_.ordinalTable, 0, _EXPORT_TABLE_.numberOfExports * sizeof(u16) );
    const Elf32_Ehdr &elfHdr = * (Elf32_Ehdr*) elf;
    DPRINTK( "\nIDynamicLoadingImpl::loadModule ELF magic header check: %b e_phoff=%x e_shoff=%u",
            __builtin_memcmp( elfHdr.e_ident, ELFMAG, 4 ) == 0,
            elfHdr.e_phoff, elfHdr.e_shoff  );

    Elf32_Shdr *sectionHeaders = (Elf32_Shdr*) (((u8*)&elfHdr) + elfHdr.e_shoff);
    Elf32_Shdr &stringTableHdr = sectionHeaders[ elfHdr.e_shstrndx ];
    const char * const stringTable = ((const char*) &elfHdr) + stringTableHdr.sh_offset;

    typedef int (*initModuleFunc)( MyOS::Context::IContext& context ) REGPARM(1);
    initModuleFunc initModule = 0;

    int dynamicLinks = 0;
    Elf32_Off PC_delta = relocateCode( elfHdr );
    int i = 0;
    for ( u8* ph = ((u8*)&elfHdr) + elfHdr.e_shoff; i < elfHdr.e_shnum; ph += elfHdr.e_shentsize, ++i) {
        Elf32_Shdr *sh = (Elf32_Shdr*) ph;
        //DPRINTK( "\nsectionHeader: name=%s type=%x size=%u", &stringTable[ sh->sh_name ],
        //        sh->sh_type, sh->sh_size );

        switch ( sh->sh_type )
        {
        /*case SHT_PROGBITS:  // remap code section(s)
            if (sh->sh_flags & SHF_EXECINSTR) {
                // DPRINTK( "\nsectionHeader: name=%s type=%x size=%u", &stringTable[ sh->sh_name ],
                //        sh->sh_type, sh->sh_size );
                sh->sh_addr = (Elf32_Addr) (elf + sh->sh_offset);    // keep original address
                sh->sh_offset += PC_delta;
            }
            break;*/

        // cannot do this here: too late in file
        // case SHT_NOBITS:

        case SHT_REL:
          {
            // DPRINTK( "\nRelocation section link=%u", sh->sh_link );

            // patch section indicated by sh->info, with symbols in sh->link section
            u8 *toPatch = ((u8*)&elfHdr) + sectionHeaders[ sh->sh_info ].sh_offset;
            //if ( sectionHeaders[ sh->sh_info ].sh_flags & SHF_EXECINSTR ) {
            //    toPatch -= PC_delta;    // correct it!
            //}

            Elf32_Shdr &symbolTH = sectionHeaders[ sh->sh_link ];
            Elf32_Sym *symbols = (Elf32_Sym*) (((u8*)&elfHdr) + symbolTH.sh_offset);
            Elf32_Shdr &symbolNameTHdr = sectionHeaders[ symbolTH.sh_link ];
            const char * const symNames = ((const char*) &elfHdr) + symbolNameTHdr.sh_offset;

            int j = 0;
            for ( Elf32_Rel *r = (Elf32_Rel*) (((u8*)&elfHdr) + sh->sh_offset);
                j < sh->sh_size; ++r, j += sh->sh_entsize ) {
                Elf32_Sym &sym = symbols[ ELF32_R_SYM( r->r_info ) ];
                u32 type = ELF32_R_TYPE( r->r_info );

                // DPRINTK( "\ni=%u type=%u name=%s offset=%u cur_value=%u", ELF32_R_SYM( r->r_info ), type,
                //        &symNames[ sym.st_name ], r->r_offset, *((u32*) &toPatch[ r->r_offset ]) );

                // Resolve undefined symbols via kernel
                u32 address = 0;
                if ( sym.st_shndx == SHN_UNDEF ) {
                    address = resolveKernelSymbol( &symNames[ sym.st_name ] );
                    if (!address) return false;     // abort

                    // DPRINTK( " %u:=%x (%s),", r->r_offset, address, &symNames[ sym.st_name ]  );

                    // For code addresses, adjust location? no
                    //if ( address < 0xffa00000 ) {
                    //    address -= PC_delta;
                    //}

                } else if ( sym.st_shndx <= elfHdr.e_shnum ) { // <= ??? or < ???
                    Elf32_Shdr &hdr = sectionHeaders[ sym.st_shndx ];

                    // For .bss and any other NOBITS sections, allocate (TODO page on demand? zeroed)
                    if ( hdr.sh_type == SHT_NOBITS ) {
                        unsigned order = bytes2order( hdr.sh_size );
                        u32 *bss = (u32*) LDComponent::getInstance().iVirtualMemory->allocate( order );
                        memset_aligned( bss, 0, hdr.sh_size );
                        ASSERTIONv( ( (u32) bss & (hdr.sh_addralign-1)) == 0, E_ERROR, hdr.sh_addralign );
                        // DPRINTK( "\nAllocated .bss@%x size=%u (2^%u pages)", bss, hdr.sh_size, order );
                        hdr.sh_offset = ((Elf32_Off) bss) - (Elf32_Off) elf;   // store in member
                        hdr.sh_type = SHT_LOUSER;
                    }

                    // For known symbols, index identifies the section
                    address = ((u32) &elfHdr) + hdr.sh_offset + sym.st_value;

                    // Undo -PC_delta on line 263 for module-internal relocations
                    if ( ELF32_ST_TYPE( sym.st_info ) == STT_FUNC || (hdr.sh_flags & SHF_EXECINSTR) ) {
                        address += PC_delta;
                    }

                    // DPRINTK( "%u:=%x (%s) type=%u,",
                    //        r->r_offset, address, &symNames[ sym.st_name ], ELF32_ST_TYPE( sym.st_info ) );
                } else continue;

                switch ( type )
                {
                /**
                 * Absolute, used for variable references in the .text segment, and
                 * class tables (i.e. function pointer (virtual method) refs
                 *  & class type info) in the .rdata segment
                 *
                 * Also e.g. personality routine is linked as absolute function pointer
                 */
                case R_386_32:   // S+A
                 {
                    *((u32*) &toPatch[ r->r_offset ]) += address;
                    break;
                 }

                /**
                 * EIP-relative, used for function calls (both internally in the module & to the OS)
                 */
                case R_386_PC32: // S+A-P
                 {
                    // DPRINTK( "\nPatch relative @%x", &toPatch[ r->r_offset ] );
                    *((u32*) &toPatch[ r->r_offset ]) += (address - (u32) (&toPatch[r->r_offset]) - 4 - PC_delta );
                    break;
                 }

                default:
                    BUG( "Unsupported relocation type" );
                }
                ++dynamicLinks;
            }
            break;
          }

        case SHT_SYMTAB:    // look for '_initModule'
         {
             Elf32_Sym *symbols = (Elf32_Sym*) (((u8*)&elfHdr) + sh->sh_offset);
             Elf32_Shdr &symbolNameTHdr = sectionHeaders[ sh->sh_link ];
             const char * const symNames = ((const char*) &elfHdr) + symbolNameTHdr.sh_offset;
             for ( int s=0, i=0; s < sh->sh_size; s+=sh->sh_entsize, ++i ) {
                 Elf32_Sym &sym = symbols[ i ];
                 if ( strncmp( "_initModule", &symNames[ sym.st_name ], 11 ) == 0) {
                     u32 address = ((u32) &elfHdr) + sectionHeaders[ sym.st_shndx ].sh_offset + sym.st_value;
                     DPRINTK( "\n#7f#Found initModule @%x", address );
                     initModule = (initModuleFunc) (address + PC_delta);
                     break;
                 }
             }
             break;
         }

        } // switch
    } // for

    /* Unmap code from data regions, only if larger than 1 page
    for ( u8* ph = ((u8*)&elfHdr) + elfHdr.e_shoff, i=0; i < elfHdr.e_shnum; ph += elfHdr.e_shentsize, ++i) {
        Elf32_Shdr *sh = (Elf32_Shdr*) ph;
        if ( sh->sh_type == SHT_LOUSER + 1 ) {
            LDComponent::getInstance().iVirtualMemory->unmap( (void*) sh->sh_addr,
                    bytes2order( sh->sh_size ) );
            DPRINTK( "\nUnmapped code@%x", sh->sh_addr );
        }
    }*/

    if ( initModule ) {
        DPRINTK( "\n#1f#Invoking initModule @%x after %u links", initModule, dynamicLinks );

        /* Show counters
        for ( int i = 0; i < _EXPORT_TABLE_.numberOfExports; ++i ) {
            if ( _EXPORT_TABLE_.ordinalTable[i] > 10 ) {
                DPRINTK( "\nSymbol %s: %u", _EXPORT_TABLE_.functionNameTable[i], _EXPORT_TABLE_.ordinalTable[i] );
            }
        }*/

        // init thread has no try...catch yet, do that here!
        try {
            // ASMVOLATILE( "nop" );
            initModule( context );
        } catch (...) {
            DPRINTK( "\n#4f#Exception during initModule" );
        }
        return true;
    } else {
        PRINTK( "\n#3f#Cannot run module: _initModule not found" );
        return false;
    }
}

bool
IDynamicLoadingImpl::loadInitialModule( Context::IContext &context )    // INITSECTION
{
    return loadModule( (u8*) &_START_OF_MODULE_, context );
}

}}
